<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                'cat_id' => 1,
                'prd_image' => 'iPhone-7-Plus-32GB-Rose-Gold.png',
                'prd_name' => 'iPhone 7 Plus 32GB Rose Gold',
                'prd_accessories' => 'Hộp, sách, sạc, cáp, tai nghe',
                'prd_price' => 10000000,
                'prd_warranty' => '12 Tháng',
                'prd_promotion' => 'Dán Màn Hình 4D',
                'prd_status' => 1,
                'prd_new' => 'Máy Mới 100%',
                'prd_details' => 'Sản phẩm này chúng tôi đang cập nhật nội dung chi tiết, các bạn có thể qua trực tiếp cửa hàng để xem sản phẩm, vì hàng chúng tôi luôn có sẵn.',
                'prd_featured' => 1,
            ],
            [
                'cat_id' => 1,
                'prd_image' => 'iPhone-X-256GB-Silver-Seedstock.png',
                'prd_name' => 'iPhone X 256GB Silver Seedstock',
                'prd_accessories' => 'Hộp, sách, sạc, cáp, tai nghe',
                'prd_price' => 10000000,
                'prd_warranty' => '12 Tháng',
                'prd_promotion' => 'Dán Màn Hình 4D',
                'prd_status' => 1,
                'prd_new' => 'Máy Mới 100%',
                'prd_details' => 'Sản phẩm này chúng tôi đang cập nhật nội dung chi tiết, các bạn có thể qua trực tiếp cửa hàng để xem sản phẩm, vì hàng chúng tôi luôn có sẵn.',
                'prd_featured' => 1,
            ],
            [
                'cat_id' => 1,
                'prd_image' => 'iPhone-Xr-2-Sim-64GB-Yellow.png',
                'prd_name' => 'iPhone Xr 2 Sim 64GB Yellow',
                'prd_accessories' => 'Hộp, sách, sạc, cáp, tai nghe',
                'prd_price' => 10000000,
                'prd_warranty' => '12 Tháng',
                'prd_promotion' => 'Dán Màn Hình 4D',
                'prd_status' => 0,
                'prd_new' => 'Máy Mới 100%',
                'prd_details' => 'Sản phẩm này chúng tôi đang cập nhật nội dung chi tiết, các bạn có thể qua trực tiếp cửa hàng để xem sản phẩm, vì hàng chúng tôi luôn có sẵn.',
                'prd_featured' => 1,
            ],
            [
                'cat_id' => 1,
                'prd_image' => 'iPhone-Xr-2-Sim-256GB-Red.png',
                'prd_name' => 'iPhone Xr 2 Sim 56GB Red',
                'prd_accessories' => 'Hộp, sách, sạc, cáp, tai nghe',
                'prd_price' => 10000000,
                'prd_warranty' => '12 Tháng',
                'prd_promotion' => 'Dán Màn Hình 4D',
                'prd_status' => 1,
                'prd_new' => 'Máy Mới 100%',
                'prd_details' => 'Sản phẩm này chúng tôi đang cập nhật nội dung chi tiết, các bạn có thể qua trực tiếp cửa hàng để xem sản phẩm, vì hàng chúng tôi luôn có sẵn.',
                'prd_featured' => 0,
            ],
            [
                'cat_id' => 1,
                'prd_image' => 'iPhone-Xs-256GB-Gold.png',
                'prd_name' => 'iPhone Xs 256GB Gold',
                'prd_accessories' => 'Hộp, sách, sạc, cáp, tai nghe',
                'prd_price' => 10000000,
                'prd_warranty' => '12 Tháng',
                'prd_promotion' => 'Dán Màn Hình 4D',
                'prd_status' => 1,
                'prd_new' => 'Máy Mới 100%',
                'prd_details' => 'Sản phẩm này chúng tôi đang cập nhật nội dung chi tiết, các bạn có thể qua trực tiếp cửa hàng để xem sản phẩm, vì hàng chúng tôi luôn có sẵn.',
                'prd_featured' => 1,
            ],
            [
                'cat_id' => 2,
                'prd_image' => 'Samsung-Galaxy-A9-2018-Black.png',
                'prd_name' => 'Samsung Galaxy A9 2018 Black',
                'prd_accessories' => 'Hộp, sách, sạc, cáp, tai nghe',
                'prd_price' => 10000000,
                'prd_warranty' => '12 Tháng',
                'prd_promotion' => 'Dán Màn Hình 4D',
                'prd_status' => 1,
                'prd_new' => 'Máy Mới 100%',
                'prd_details' => 'Sản phẩm này chúng tôi đang cập nhật nội dung chi tiết, các bạn có thể qua trực tiếp cửa hàng để xem sản phẩm, vì hàng chúng tôi luôn có sẵn.',
                'prd_featured' => 0,
            ],
            [
                'cat_id' => 2,
                'prd_image' => 'Samsung-Galaxy-J2-Core-Gold.png',
                'prd_name' => 'Samsung Galaxy J2 Core Gold',
                'prd_accessories' => 'Hộp, sách, sạc, cáp, tai nghe',
                'prd_price' => 10000000,
                'prd_warranty' => '12 Tháng',
                'prd_promotion' => 'Dán Màn Hình 4D',
                'prd_status' => 1,
                'prd_new' => 'Máy Mới 100%',
                'prd_details' => 'Sản phẩm này chúng tôi đang cập nhật nội dung chi tiết, các bạn có thể qua trực tiếp cửa hàng để xem sản phẩm, vì hàng chúng tôi luôn có sẵn.',
                'prd_featured' => 1,
            ],
            [
                'cat_id' => 2,
                'prd_image' => 'Samsung-Galaxy-J4-Core-Black.png',
                'prd_name' => 'Samsung Galaxy J4 Core Black',
                'prd_accessories' => 'Hộp, sách, sạc, cáp, tai nghe',
                'prd_price' => 10000000,
                'prd_warranty' => '12 Tháng',
                'prd_promotion' => 'Dán Màn Hình 4D',
                'prd_status' => 1,
                'prd_new' => 'Máy Mới 100%',
                'prd_details' => 'Sản phẩm này chúng tôi đang cập nhật nội dung chi tiết, các bạn có thể qua trực tiếp cửa hàng để xem sản phẩm, vì hàng chúng tôi luôn có sẵn.',
                'prd_featured' => 1,
            ],
            [
                'cat_id' => 2,
                'prd_image' => 'Samsung Galaxy S9 Plus 64GB Orchid Gray',
                'prd_name' => 'Samsung-Galaxy-S9-Plus-64GB-Orchid-Gray.png',
                'prd_accessories' => 'Hộp, sách, sạc, cáp, tai nghe',
                'prd_price' => 10000000,
                'prd_warranty' => '12 Tháng',
                'prd_promotion' => 'Dán Màn Hình 4D',
                'prd_status' => 1,
                'prd_new' => 'Máy Mới 100%',
                'prd_details' => 'Sản phẩm này chúng tôi đang cập nhật nội dung chi tiết, các bạn có thể qua trực tiếp cửa hàng để xem sản phẩm, vì hàng chúng tôi luôn có sẵn.',
                'prd_featured' => 1,
            ],
            [
                'cat_id' => 2,
                'prd_image' => 'Samsung-Galaxy-S9-Plus-Black-128GB.png',
                'prd_name' => 'Samsung Galaxy S9 Plus Black 128GB',
                'prd_accessories' => 'Hộp, sách, sạc, cáp, tai nghe',
                'prd_price' => 10000000,
                'prd_warranty' => '12 Tháng',
                'prd_promotion' => 'Dán Màn Hình 4D',
                'prd_status' => 1,
                'prd_new' => 'Máy Mới 100%',
                'prd_details' => 'Sản phẩm này chúng tôi đang cập nhật nội dung chi tiết, các bạn có thể qua trực tiếp cửa hàng để xem sản phẩm, vì hàng chúng tôi luôn có sẵn.',
                'prd_featured' => 1,
            ],
            [
                'cat_id' => 4,               
                 'prd_image' => 'Nokia 1 red',
                'prd_name' => 'Nokia-1-red.png',
                'prd_accessories' => 'Hộp, sách, sạc, cáp, tai nghe',
                'prd_price' => 10000000,
                'prd_warranty' => '12 Tháng',
                'prd_promotion' => 'Dán Màn Hình 4D',
                'prd_status' => 1,
                'prd_new' => 'Máy Mới 100%',
                'prd_details' => 'Sản phẩm này chúng tôi đang cập nhật nội dung chi tiết, các bạn có thể qua trực tiếp cửa hàng để xem sản phẩm, vì hàng chúng tôi luôn có sẵn.',
                'prd_featured' => 1,
            ],
            [
                'cat_id' => 4,                
                'prd_image' => 'Nokia-3.1-Black.png',
                'prd_name' => 'Nokia 3.1 Black',
                'prd_accessories' => 'Hộp, sách, sạc, cáp, tai nghe',
                'prd_price' => 10000000,
                'prd_warranty' => '12 Tháng',
                'prd_promotion' => 'Dán Màn Hình 4D',
                'prd_status' => 1,
                'prd_new' => 'Máy Mới 100%',
                'prd_details' => 'Sản phẩm này chúng tôi đang cập nhật nội dung chi tiết, các bạn có thể qua trực tiếp cửa hàng để xem sản phẩm, vì hàng chúng tôi luôn có sẵn.',
                'prd_featured' => 1,
            ],
            [
                'cat_id' => 4,
                'prd_image' => 'Nokia-6.1-Plus-Blue.png',
                'prd_name' => 'Nokia 6.1 Plus Blue',
                'prd_accessories' => 'Hộp, sách, sạc, cáp, tai nghe',
                'prd_price' => 10000000,
                'prd_warranty' => '12 Tháng',
                'prd_promotion' => 'Dán Màn Hình 4D',
                'prd_status' => 1,
                'prd_new' => 'Máy Mới 100%',
                'prd_details' => 'Sản phẩm này chúng tôi đang cập nhật nội dung chi tiết, các bạn có thể qua trực tiếp cửa hàng để xem sản phẩm, vì hàng chúng tôi luôn có sẵn.',
                'prd_featured' => 1,
            ],
            [
                'cat_id' => 4,                
                'prd_image' => 'Nokia-6.1-Plus-White.png',
                'prd_name' => 'Nokia 6.1 Plus White',
                'prd_accessories' => 'Hộp, sách, sạc, cáp, tai nghe',
                'prd_price' => 10000000,
                'prd_warranty' => '12 Tháng',
                'prd_promotion' => 'Dán Màn Hình 4D',
                'prd_status' => 1,
                'prd_new' => 'Máy Mới 100%',
                'prd_details' => 'Sản phẩm này chúng tôi đang cập nhật nội dung chi tiết, các bạn có thể qua trực tiếp cửa hàng để xem sản phẩm, vì hàng chúng tôi luôn có sẵn.',
                'prd_featured' => 1,
            ],
            [
                'cat_id' => 4,
                'prd_image' => 'Nokia-150-White.png',
                'prd_name' => 'Nokia 150 White',
                'prd_accessories' => 'Hộp, sách, sạc, cáp, tai nghe',
                'prd_price' => 10000000,
                'prd_warranty' => '12 Tháng',
                'prd_promotion' => 'Dán Màn Hình 4D',
                'prd_status' => 1,
                'prd_new' => 'Máy Mới 100%',
                'prd_details' => 'Sản phẩm này chúng tôi đang cập nhật nội dung chi tiết, các bạn có thể qua trực tiếp cửa hàng để xem sản phẩm, vì hàng chúng tôi luôn có sẵn.',
                'prd_featured' => 1,
            ],
            [
                'cat_id' => 7,
                'prd_image' => 'OPPO-A3s–16GB-Red.png',
                'prd_name' => 'OPPO A3s 16GB Red',
                'prd_accessories' => 'Hộp, sách, sạc, cáp, tai nghe',
                'prd_price' => 10000000,
                'prd_warranty' => '12 Tháng',
                'prd_promotion' => 'Dán Màn Hình 4D',
                'prd_status' => 1,
                'prd_new' => 'Máy Mới 100%',
                'prd_details' => 'Sản phẩm này chúng tôi đang cập nhật nội dung chi tiết, các bạn có thể qua trực tiếp cửa hàng để xem sản phẩm, vì hàng chúng tôi luôn có sẵn.',
                'prd_featured' => 1,
            ],
            [
                'cat_id' => 7,
                'prd_image' => 'OPPO-A7-64GB-Blue.png',
                'prd_name' => 'OPPO A7 64GB Blue',
                'prd_accessories' => 'Hộp, sách, sạc, cáp, tai nghe',
                'prd_price' => 10000000,
                'prd_warranty' => '12 Tháng',
                'prd_promotion' => 'Dán Màn Hình 4D',
                'prd_status' => 1,
                'prd_new' => 'Máy Mới 100%',
                'prd_details' => 'Sản phẩm này chúng tôi đang cập nhật nội dung chi tiết, các bạn có thể qua trực tiếp cửa hàng để xem sản phẩm, vì hàng chúng tôi luôn có sẵn.',
                'prd_featured' => 1,
            ],

        ];

        DB::table('products')->insert($data);
    }
}
